//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace StocksWithFriends.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DBEntities object using the connection string found in the 'DBEntities' section of the application configuration file.
        /// </summary>
        public DBEntities() : base("name=DBEntities", "DBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DBEntities object.
        /// </summary>
        public DBEntities(string connectionString) : base(connectionString, "DBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DBEntities object.
        /// </summary>
        public DBEntities(EntityConnection connection) : base(connection, "DBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<CalendarEvent> CalendarEvents
        {
            get
            {
                if ((_CalendarEvents == null))
                {
                    _CalendarEvents = base.CreateObjectSet<CalendarEvent>("CalendarEvents");
                }
                return _CalendarEvents;
            }
        }
        private ObjectSet<CalendarEvent> _CalendarEvents;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the CalendarEvents EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCalendarEvents(CalendarEvent calendarEvent)
        {
            base.AddObject("CalendarEvents", calendarEvent);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DBModel", Name="CalendarEvent")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CalendarEvent : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new CalendarEvent object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="user_id">Initial value of the user_id property.</param>
        public static CalendarEvent CreateCalendarEvent(global::System.Int32 id, global::System.Int32 user_id)
        {
            CalendarEvent calendarEvent = new CalendarEvent();
            calendarEvent.id = id;
            calendarEvent.user_id = user_id;
            return calendarEvent;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 user_id
        {
            get
            {
                return _user_id;
            }
            set
            {
                Onuser_idChanging(value);
                ReportPropertyChanging("user_id");
                _user_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("user_id");
                Onuser_idChanged();
            }
        }
        private global::System.Int32 _user_id;
        partial void Onuser_idChanging(global::System.Int32 value);
        partial void Onuser_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String event_name
        {
            get
            {
                return _event_name;
            }
            set
            {
                Onevent_nameChanging(value);
                ReportPropertyChanging("event_name");
                _event_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("event_name");
                Onevent_nameChanged();
            }
        }
        private global::System.String _event_name;
        partial void Onevent_nameChanging(global::System.String value);
        partial void Onevent_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String event_description
        {
            get
            {
                return _event_description;
            }
            set
            {
                Onevent_descriptionChanging(value);
                ReportPropertyChanging("event_description");
                _event_description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("event_description");
                Onevent_descriptionChanged();
            }
        }
        private global::System.String _event_description;
        partial void Onevent_descriptionChanging(global::System.String value);
        partial void Onevent_descriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> start_timestamp
        {
            get
            {
                return _start_timestamp;
            }
            set
            {
                Onstart_timestampChanging(value);
                ReportPropertyChanging("start_timestamp");
                _start_timestamp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("start_timestamp");
                Onstart_timestampChanged();
            }
        }
        private Nullable<global::System.DateTime> _start_timestamp;
        partial void Onstart_timestampChanging(Nullable<global::System.DateTime> value);
        partial void Onstart_timestampChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> end_timestamp
        {
            get
            {
                return _end_timestamp;
            }
            set
            {
                Onend_timestampChanging(value);
                ReportPropertyChanging("end_timestamp");
                _end_timestamp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("end_timestamp");
                Onend_timestampChanged();
            }
        }
        private Nullable<global::System.DateTime> _end_timestamp;
        partial void Onend_timestampChanging(Nullable<global::System.DateTime> value);
        partial void Onend_timestampChanged();

        #endregion

    
    }

    #endregion

    
}
